# Generated by Django 6.0 on 2025-12-30 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Q1', 'Quiosque 1'), ('Q2', 'Quiosque 2'), ('Q3', 'Quiosque 3'), ('Q4', 'Quiosque 4'), ('Q5', 'Quiosque 5'), ('Q6', 'Quiosque 6')], max_length=2, unique=True, verbose_name='Nome do Quiosque')),
                ('capacidade_maxima', models.PositiveIntegerField(verbose_name='Capacidade Máxima de Pessoas')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Diária (R$)')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Reserva')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='quiosques/', verbose_name='Imagem do Quiosque')),
            ],
            options={
                'verbose_name': 'Quiosque',
                'verbose_name_plural': 'Quiosques',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=10, unique=True, verbose_name='Número do Lote')),
                ('proprietario', models.CharField(max_length=100, verbose_name='Nome do Proprietário')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de Contato')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Vinculado')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['numero_lote'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(verbose_name='Data da Reserva')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('quantidade_pessoas', models.PositiveIntegerField(verbose_name='Quantidade de Pessoas')),
                ('confirmada', models.BooleanField(default=False, verbose_name='Reserva Confirmada')),
                ('valor_reserva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Reserva (R$)')),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante de Pagamento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas_quiosques.lote', verbose_name='Lote')),
                ('quiosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas_quiosques.quiosque', verbose_name='Quiosque')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_reserva'],
                'unique_together': {('quiosque', 'data_reserva')},
            },
        ),
    ]
