# Generated by Django 6.0 on 2025-12-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_quiosques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiosque',
            name='nome',
            field=models.CharField(choices=[('AZ', 'Azaléia'), ('PR', 'Primavera')], max_length=2, unique=True, verbose_name='Nome do Quiosque'),
        ),
    ]
