# Generated by Django 5.1.6 on 2026-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas_quiosques", "0002_alter_quiosque_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="comprovante_pagamento",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Comprovante de Pagamento",
            ),
        ),
    ]
