# Generated by Django 5.1.6 on 2026-06-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_quiosques', '0003_alter_reserva_comprovante_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Usuário Bloqueado'),
        ),
    ]
